---
version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/node:lts
        environment:
          NODE_ENV: test
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - setup_remote_docker
      - run: |
          sudo corepack enable
          cat \<< EOF > .yarnrc.yml
          approvedGitRepositories:
            - https://github.com/laboperator-gmbh/*
          nodeLinker: node-modules
          EOF
      - run: yarn add --dev middleware-development@laboperator-gmbh/middleware-development#$CIRCLE_SHA1
      - run: yarn middleware init
      # disable until middleware is updated to eslint 9
      # - run: yarn middleware lint
      - run: yarn middleware test
      - run: yarn middleware compile
      - run: yarn middleware clean
      - run: yarn middleware build test

workflows:
  version: 2

  tests:
    jobs:
      - tests
